### ISSUE TITLE
goweb as web2c ?

### ISSUE THREAD

**Issue by sbinet** [santucco/goweb#1]
hi,

apologies if that's not the intended medium to ask questions about goweb.

I am the current maintainer of github.com/go-latex/latex and I'd like to improve its math equation rendering capabilities.
I figured I could just write the full TeX engine, building on web2c.
I've stumbled on your nice WEB project in Go.

do you think it would be doable to reuse parts of goweb to have a web2go program that ingests TexLive's `tex.w` original file?

**Comment by santucco** [comment]
Hi,
I think goweb is useless in this approach.
Let me clarify:
WEB is originally Pascal with a special markup language. 
I suppose, web2c works like the tangle program, but simultaneously converts from Pascal code to C code and makes a lot of special body movements.

Goweb (gotangle) just makes Go source files from source files which already contains Golang code with a bit other markup language, than WEB.

I think, in your case a better approach is to take web2c and make it to produce Go code instead of C code and keep all other high level logic.

Yes, you  can do the same with WEB files - just convert Pascal into Go and you will get almost goweb-compatible source files.
But potentially you will lost all other logic which makes TeX to work.

**Comment by sbinet** [comment]
thanks.
I thought I could perhaps reuse the WEB parser somehow. but ok.

**Comment by santucco** [comment]
WEB parser is strongly integrated to the code. It is hard to separate it.
And it differs a bit from the original one. I based the goweb on cweb, not web, and cweb differs from the original web a bit too.
